version: '3'
services:
  backend:
    image: harshankbansal/goals-backend:prod
    ports:
      - 3000:80
    networks:
      - docker-complete-network
    env_file:
      - ./backend/docker.env

  frontend:
    image: harshankbansal/goals-frontend:prod
    ports:
      - 80:80
    networks:
      - docker-complete-network
    env_file:
      - ./frontend/docker.env

networks:
  docker-complete-network:
